name: Official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
runs:
  using: composite
  steps:
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      shell: bash

    - name: Run SonarQube Scan
      run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ inputs.args }} ${{ inputs.projectBaseDir }}
      shell: bash

    - name: Cleanup
      run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace /cleanup.sh
      shell: bash

inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .